name: unittests

on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests on ${{ matrix.os }} with ${{ matrix.toolchain.compiler }} ${{ matrix.toolchain.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-12]
        toolchain:
          - {compiler: gcc, version: 13}
        # include:
          # - os: ubuntu-latest
          #   toolchain: {nvidia-hpc, version: '23.11'}
          # - os: windows-latest
          #   toolchain: {compiler: intel, version: '2023.2'}
          # - os: windows-latest
          #   toolchain: {compiler: intel-classic, version: '2021.10'}
        # exclude:
        #   - os: windows-latest
        #     toolchain: {compiler: gcc, version: 13}

    steps:
      - uses: actions/checkout@v4
      - name: checkout submodules
        run: git submodule update --init --recursive

      - uses: fortran-lang/setup-fortran@v1
        if: matrix.os != 'macos-12'
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      
      - name: Setup gfortran macos-12
        if: matrix.os == 'macos-12'
        run: |
          export FC=$(which gfortran-13)
          echo FC=$FC >> $GITHUB_ENV

      - name: Build ThermoPack
        if: matrix.os != 'windows-latest'
        run: |
          mkdir build
          cd build
          cmake -Dtest=ON -DCMAKE_BUILD_TYPE=Debug ..
          make -j4 install
      
      - name: Build ThermoPack Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "Building on ${{ matrix.os }}"
          setx FC "${{ env.FC }}"
          setx FC_PATH "$(Get-Command ${{ env.FC }}).Path"
          echo "Using compiler $env:FC / ${{ env.FC }}"
          echo "gfortran at $(Get-Command ${{ env.FC }}).Path / $env:FC_PATH"
          mkdir build
          cd build
          cmake .. -Dtest=ON -DCMAKE_Fortran_COMPILER=$(Get-Command ${{ env.FC }}).Path
          cmake --build . --target INSTALL
    
      - name: Inspect thermopack
        if: matrix.os == 'ubuntu'
        run: | 
          echo "--- Inspecting libthermopack ---"
          ldd installed/libthermopack.so
          echo "--- Inspecting run_unittests ---"
          ldd installed/unittests

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: binary-${{ matrix.os }}
            path: ./installed/*
    
      - id: fortran_test
        name: Run unittests
        continue-on-error: true
        run: |
            result=$(./installed/unittests)
            if echo "$result" | grep -q "OK"; then
            statuscode=0
            else
            statuscode=1
            fi
            echo "$result"
            echo "statuscode=$statuscode" >> $GITHUB_OUTPUT
            exit $statuscode
            
      - uses: actions/setup-python@v5
      - id: python_test 
        name: Run python tests
        continue-on-error: true
        run: |
            python addon/pycThermopack/map_platform_specifics.py
            pip install addon/pycThermopack/[test]
            pytest addon/pyTests
            result=$(pytest addon/pyTests)
            if echo "$result" | grep -q "FAILED"; then
            statuscode=1
            else
            statuscode=0
            fi
            echo "$result"
            echo "statuscode=$statuscode" >> $GITHUB_OUTPUT
            exit $statuscode
    
      - name: Check success
        run: |
            echo "Fortran test result : ${{ steps.fortran_test.outputs.statuscode }}"
            echo "Python test result : ${{ steps.python_test.outputs.statuscode }}"
            if [[ ${{ steps.fortran_test.outputs.statuscode }} -eq 0 ]] && [[ ${{ steps.python_test.outputs.statuscode }} -eq 0 ]]; then
            exit 0
            else
            exit 1
            fi
        


    
            